name: Playwright Tests
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
      AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
      AGORA_TOKEN: ${{ secrets.AGORA_TOKEN }}
      AGORA_CHANNEL: ${{ secrets.AGORA_CHANNEL }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Single User Tests
      run: npx playwright test --project=single-user
    - name: Run Multi User Tests
      run: npx playwright test --project=multi-user
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
