name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Setup & Install
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --user 1001
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

  test:
    name: Playwright Tests
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
      options: --user 1001
    timeout-minutes: 60
    env:
      NODE_ENV: ci
      AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
      AGORA_TOKEN: ${{ secrets.AGORA_TOKEN }}
      AGORA_CHANNEL: ${{ secrets.AGORA_CHANNEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore node_modules Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Ensure CTRF report directory exists
        run: mkdir -p ctrf/reports/e2e

      - name: Run All Tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" npm run test

      - name: Upload E2E Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: |
            reports/e2e
            ctrf/reports/e2e
          retention-days: 14

      - name: Publish Test Report (CTRF JSON)
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: ctrf/reports/e2e/ctrf.json
      
      - name: Upload Snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: snapshots/ci
          retention-days: 14